# Generated by Django 3.0.7 on 2020-08-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('fb', models.URLField(blank=True, null=True)),
                ('twiter', models.URLField(blank=True, null=True)),
                ('insta', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
